---
- name: Create Istio system namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.system.namespace }}"
        labels:
          istio-injection: enabled
          it-bench/monitoring: "true"

- name: Install Istio base
  kubernetes.core.helm:
    release_name: istio-base
    chart_ref: base
    chart_repo_url: https://istio-release.storage.googleapis.com/charts
    release_namespace: "{{ helm_release.system.namespace }}"
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_state: present
    values:
      defaultRevision: "default"
    wait: true

- name: Install Istiod control plane
  kubernetes.core.helm:
    release_name: istiod
    chart_ref: istiod
    chart_repo_url: https://istio-release.storage.googleapis.com/charts
    release_namespace: "{{ helm_release.system.namespace }}"
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_state: present
    wait: true

- name: Create Istio ingress gateway namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.ingress.namespace }}"
        labels:
          istio-injection: enabled
          it-bench/monitoring: "true"

- name: Install Istio ingress gateway
  kubernetes.core.helm:
    release_name: "{{ helm_release.ingress.name }}"
    chart_ref: gateway
    chart_repo_url: https://istio-release.storage.googleapis.com/charts
    release_namespace: "{{ helm_release.ingress.namespace }}"
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_state: present
    values:
      service:
        type: NodePort
        nodePorts:
          http: 8123
    wait: true

- name: Wait for Istio pods to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ helm_release.system.namespace }}"
    label_selectors:
      - app=istiod
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
